-- Seed additional site_config keys for auth, checkout, and blog detail customization
insert into public.site_config(key, value) values
  ('login_title', 'Đăng Nhập'),
  ('login_email_placeholder', 'Email'),
  ('login_password_placeholder', 'Mật khẩu'),
  ('login_submit_text', 'Đăng Nhập'),
  ('login_loading_text', 'Đang đăng nhập...'),
  ('login_forgot_link_text', 'Quên mật khẩu?'),
  ('login_signup_prompt_text', 'Chưa có tài khoản?'),
  ('login_signup_link_text', 'Đăng ký ngay'),

  ('signup_title', 'Đăng Ký'),
  ('signup_fullname_placeholder', 'Họ và tên'),
  ('signup_email_placeholder', 'Email'),
  ('signup_password_placeholder', 'Mật khẩu (ít nhất 6 ký tự)'),
  ('signup_submit_text', 'Đăng Ký'),
  ('signup_loading_text', 'Đang đăng ký...'),
  ('signup_login_prompt_text', 'Đã có tài khoản?'),
  ('signup_login_link_text', 'Đăng nhập'),
  ('signup_check_email_title', 'Kiểm tra email của bạn'),
  ('signup_check_email_description', 'Chúng tôi đã gửi email xác nhận tới'),
  ('signup_back_to_login_text', 'Quay lại đăng nhập'),

  ('forgot_title', 'Quên mật khẩu'),
  ('forgot_description', 'Nhập email của bạn, chúng tôi sẽ gửi link đặt lại mật khẩu.'),
  ('forgot_email_placeholder', 'Email'),
  ('forgot_submit_text', 'Gửi email đặt lại mật khẩu'),
  ('forgot_loading_text', 'Đang gửi...'),
  ('forgot_back_to_login_text', 'Quay lại đăng nhập'),
  ('forgot_check_email_title', 'Kiểm tra email'),
  ('forgot_check_email_description', 'Chúng tôi đã gửi hướng dẫn đặt lại mật khẩu tới'),

  ('reset_invalid_title', 'Liên kết không hợp lệ'),
  ('reset_invalid_description', 'Link đặt lại mật khẩu không hợp lệ hoặc đã hết hạn.'),
  ('reset_request_again_text', 'Yêu cầu lại'),
  ('reset_success_title', 'Đặt lại thành công!'),
  ('reset_success_description', 'Mật khẩu đã được cập nhật. Đang chuyển tới trang đăng nhập...'),
  ('reset_title', 'Đặt lại mật khẩu'),
  ('reset_password_placeholder', 'Mật khẩu mới (ít nhất 6 ký tự)'),
  ('reset_confirm_password_placeholder', 'Xác nhận mật khẩu mới'),
  ('reset_submit_text', 'Đặt lại mật khẩu'),
  ('reset_loading_text', 'Đang xử lý...'),

  ('checkout_title', 'Thanh Toán'),
  ('checkout_empty_cart_title', 'Giỏ hàng trống'),
  ('checkout_continue_shopping_text', 'Tiếp tục mua sắm'),
  ('checkout_shipping_title', 'Thông tin giao hàng'),
  ('checkout_fullname_placeholder', 'Họ và tên *'),
  ('checkout_phone_placeholder', 'Số điện thoại *'),
  ('checkout_address_placeholder', 'Địa chỉ giao hàng *'),
  ('checkout_notes_placeholder', 'Ghi chú đơn hàng (tùy chọn)'),
  ('checkout_invoice_toggle_text', 'Yêu cầu xuất hóa đơn VAT'),
  ('checkout_invoice_company_placeholder', 'Tên công ty *'),
  ('checkout_invoice_tax_code_placeholder', 'Mã số thuế *'),
  ('checkout_invoice_address_placeholder', 'Địa chỉ công ty *'),
  ('checkout_invoice_email_placeholder', 'Email nhận hóa đơn *'),
  ('checkout_submit_text', 'Xác nhận đặt hàng'),
  ('checkout_loading_text', 'Đang xử lý...'),
  ('checkout_summary_title', 'Đơn hàng'),
  ('checkout_summary_subtotal_text', 'Tạm tính'),
  ('checkout_summary_shipping_text', 'Phí vận chuyển'),
  ('checkout_summary_shipping_free_text', 'Miễn phí'),
  ('checkout_summary_total_text', 'Tổng cộng'),
  ('checkout_login_required_text', 'Vui lòng đăng nhập để đặt hàng'),
  ('checkout_order_failed_text', 'Đặt hàng thất bại'),
  ('checkout_items_failed_text', 'Lỗi khi lưu chi tiết đơn hàng'),
  ('checkout_success_title', 'Đặt hàng thành công!'),
  ('checkout_success_description', 'Chúng tôi sẽ liên hệ xác nhận đơn hàng sớm nhất.'),

  ('blog_detail_not_found_title', 'Bài viết không tồn tại'),
  ('blog_detail_back_to_blog_text', 'Quay lại trang Blog'),
  ('blog_detail_back_text', 'Quay lại'),
  ('blog_detail_author_name', 'Phúc Vinh Solar'),
  ('blog_detail_content_fallback', 'Nội dung chi tiết đang được cập nhật. Bạn có thể liên hệ để nhận tư vấn thêm ngay hôm nay.')
on conflict (key) do nothing;
