-- Run this entire script in your Supabase Dashboard -> SQL Editor

-- 1. Ensure enum app_role exists (catch duplicate)
DO $$
BEGIN
    CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
EXCEPTION WHEN duplicate_object THEN
    NULL;
END
$$;

-- 2. Ensure user_roles table exists
CREATE TABLE IF NOT EXISTS public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role public.app_role NOT NULL,
  UNIQUE (user_id, role)
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- 3. Ensure bucket exists and has the correct policies
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true) 
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Public can read product images" ON storage.objects;
  DROP POLICY IF EXISTS "Admins can upload product images" ON storage.objects;
  DROP POLICY IF EXISTS "Admins can update product images" ON storage.objects;
  DROP POLICY IF EXISTS "Admins can delete product images" ON storage.objects;
EXCEPTION WHEN undefined_table THEN
  NULL;
END
$$;

CREATE POLICY "Public can read product images" ON storage.objects
FOR SELECT USING (bucket_id = 'product-images');

CREATE POLICY "Admins can upload product images" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'product-images'
  AND (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'))
);

CREATE POLICY "Admins can update product images" ON storage.objects
FOR UPDATE USING (
  bucket_id = 'product-images'
  AND (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'))
)
WITH CHECK (
  bucket_id = 'product-images'
  AND (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'))
);

CREATE POLICY "Admins can delete product images" ON storage.objects
FOR DELETE USING (
  bucket_id = 'product-images'
  AND (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'))
);

-- 4. Ensure conversations and messages tables exist
CREATE TABLE IF NOT EXISTS public.conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL UNIQUE,
    status VARCHAR(60) NOT NULL DEFAULT 'open',
    unread_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Allow public select conversations" ON public.conversations;
  DROP POLICY IF EXISTS "Allow public insert conversations" ON public.conversations;
  DROP POLICY IF EXISTS "Allow public update conversations" ON public.conversations;
  DROP POLICY IF EXISTS "Conversations public select" ON public.conversations;
  DROP POLICY IF EXISTS "Conversations public insert" ON public.conversations;
EXCEPTION WHEN undefined_table THEN
  NULL;
END
$$;

CREATE POLICY "Allow public select conversations"
ON public.conversations FOR SELECT
USING (auth.uid() IS NOT NULL OR auth.role() = 'anon');

CREATE POLICY "Allow public insert conversations"
ON public.conversations FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL OR auth.role() = 'anon');

CREATE POLICY "Allow public update conversations"
ON public.conversations FOR UPDATE
USING (auth.uid() IS NOT NULL OR auth.role() = 'anon')
WITH CHECK (auth.uid() IS NOT NULL OR auth.role() = 'anon');

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT,
    content TEXT NOT NULL,
    sender VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

DO $$ BEGIN
  ALTER TABLE public.messages
    ADD CONSTRAINT messages_conversation_id_fkey
    FOREIGN KEY (conversation_id)
    REFERENCES public.conversations (id)
    ON DELETE CASCADE;
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Allow realtime access for public users" ON public.messages;
  DROP POLICY IF EXISTS "Allow insert for public users" ON public.messages;
  DROP POLICY IF EXISTS "Messages public select" ON public.messages;
  DROP POLICY IF EXISTS "Messages public insert" ON public.messages;
EXCEPTION WHEN undefined_table THEN
  NULL;
END
$$;

CREATE POLICY "Allow realtime access for public users"
ON public.messages FOR SELECT
USING (auth.uid() IS NOT NULL OR auth.role() = 'anon');

CREATE POLICY "Allow insert for public users"
ON public.messages FOR INSERT
WITH CHECK (auth.uid() IS NOT NULL OR auth.role() = 'anon');

-- 5. Fix admin roles policies using inline check
DO $$
BEGIN
  DROP POLICY IF EXISTS "Admins can view user roles" ON public.user_roles;
  DROP POLICY IF EXISTS "Admins can insert user roles" ON public.user_roles;
  DROP POLICY IF EXISTS "Admins can update user roles" ON public.user_roles;
  DROP POLICY IF EXISTS "Admins can delete user roles" ON public.user_roles;
EXCEPTION WHEN undefined_table THEN
  NULL;
END
$$;

CREATE POLICY "Admins can view user roles" ON public.user_roles
FOR SELECT USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'));

CREATE POLICY "Admins can insert user roles" ON public.user_roles
FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'));

CREATE POLICY "Admins can update user roles" ON public.user_roles
FOR UPDATE USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'))
WITH CHECK (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'));

CREATE POLICY "Admins can delete user roles" ON public.user_roles
FOR DELETE USING (EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role::text = 'admin'));

-- 6. Create RPC function for admin role updates (bypasses RLS)
CREATE OR REPLACE FUNCTION public.admin_update_user_role(
  target_user_id UUID,
  new_role TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Verify caller is admin
  IF NOT EXISTS (
    SELECT 1 FROM public.user_roles
    WHERE user_id = auth.uid() AND role = 'admin'::public.app_role
  ) THEN
    RAISE EXCEPTION 'Permission denied: only admins can change roles';
  END IF;

  -- Validate role value
  IF new_role NOT IN ('admin', 'moderator', 'user') THEN
    RAISE EXCEPTION 'Invalid role: %', new_role;
  END IF;

  -- Delete existing roles for target user
  DELETE FROM public.user_roles WHERE user_id = target_user_id;

  -- Insert the new role
  INSERT INTO public.user_roles (user_id, role)
  VALUES (target_user_id, new_role::public.app_role);
END;
$$;

-- 7. Reload PostgREST Cache so your app can see the tables!
NOTIFY pgrst, 'reload schema';
