// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

const isValidHttpUrl = (value?: string) => {
  if (!value) return false;

  try {
    const parsed = new URL(value);
    return parsed.protocol === "http:" || parsed.protocol === "https:";
  } catch {
    return false;
  }
};

const hasValidUrl = isValidHttpUrl(SUPABASE_URL);

export const isSupabaseConfigured = Boolean(hasValidUrl && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.error(
    "Invalid or missing Supabase env. Ensure VITE_SUPABASE_URL is a full http(s) URL and VITE_SUPABASE_PUBLISHABLE_KEY is set.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  (hasValidUrl ? SUPABASE_URL : undefined) || "https://example.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "public-anon-key-not-configured",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);